/*
 * This source file was generated by the Gradle 'init' task
 */
package a1;

import a1.controller.GOController;
import a1.repo.GORepository;
import a1.views.GOView;

public class App {

    public static void main(String[] args) {
        GORepository goRepo = new GORepository();
        GOController controller = new GOController(goRepo);
        GOView view = new GOView(controller);
        view.start();
    }
}
